# Generated by Django 6.0.4 on 2026-05-02 13:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_categorie_materiel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='materiel',
            name='date_acquisition',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='gestion.categorie'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='etat',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('emprunte', 'Emprunté'), ('maintenance', 'En maintenance'), ('hors_service', 'Hors service')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ConversationChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('messages', models.JSONField(default=list, help_text='Liste des messages (format JSON)')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('en_cours', 'En cours'), ('restituee', 'Restituée'), ('retard', 'En retard')], default='en_attente', max_length=20)),
                ('motif', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplacements', to='gestion.demande')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('panne', 'Panne'), ('revision', 'Révision'), ('etalonnage', 'Étalonnage'), ('reparation', 'Réparation')], max_length=20)),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('signale', 'Signalé'), ('en_cours', 'En cours'), ('resolu', 'Résolu')], default='signale', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='gestion.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Restitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_retour', models.DateTimeField(auto_now_add=True)),
                ('etat_materiel', models.TextField(blank=True, help_text='État du matériel au retour')),
                ('observations', models.TextField(blank=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restitution', to='gestion.demande')),
            ],
        ),
        migrations.CreateModel(
            name='LigneDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion.demande')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.materiel')),
            ],
            options={
                'unique_together': {('demande', 'materiel')},
            },
        ),
    ]
