# Generated by Django 6.0.4 on 2026-05-04 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_categorie_options_materiel_date_acquisition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('recuperation', 'Récupération'), ('retour', 'Retour'), ('retard', 'Retard'), ('nouvelle_demande', 'Nouvelle demande'), ('validation', 'Validation')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gestion.demande')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
