# Generated by Django 6.0.4 on 2026-05-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_maintenance_description_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='quantite_disponible',
            field=models.PositiveIntegerField(default=1, help_text="Quantité disponible à l'emprunt"),
        ),
        migrations.AddField(
            model_name='materiel',
            name='quantite_totale',
            field=models.PositiveIntegerField(default=1, help_text='Quantité totale en stock'),
        ),
    ]
