# Generated by Django 6.0.5 on 2026-05-17 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_materiel_quantite_disponible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('annulee', 'Annulee'), ('terminee', 'Terminee')], default='active', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('demande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='gestion.demande')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='gestion.materiel')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
    ]
