# Generated by Django 6.0.5 on 2026-05-17 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Deconnexion'), ('inscription', 'Inscription'), ('demande_creee', 'Demande creee'), ('demande_approuvee', 'Demande approuvee'), ('demande_refusee', 'Demande refusee'), ('materiel_recupere', 'Materiel recupere'), ('materiel_rendu', 'Materiel rendu'), ('panne_signalee', 'Panne signalee'), ('maintenance_resolue', 'Maintenance resolue'), ('materiel_ajoute', 'Materiel ajoute'), ('materiel_modifie', 'Materiel modifie'), ('materiel_supprime', 'Materiel supprime'), ('role_modifie', 'Role modifie'), ('reservation_creee', 'Reservation creee'), ('reservation_annulee', 'Reservation annulee')], max_length=30)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to='gestion.demande')),
                ('materiel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to='gestion.materiel')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal activite',
                'verbose_name_plural': 'Journal des activites',
                'ordering': ['-date'],
            },
        ),
    ]
