# Generated by Django 6.0.5 on 2026-05-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_journalactivite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('en_cours', 'En cours'), ('restituee', 'Restituée'), ('retard', 'En retard'), ('annulee', 'Annulee')], default='en_attente', max_length=20),
        ),
    ]
